# Generated by Django 3.1.8 on 2022-04-08 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apis_metainfo', '0001_initial'),
        ('apis_entities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventEvent',
            fields=[
                ('tempentityclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_metainfo.tempentityclass')),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
            bases=('apis_metainfo.tempentityclass',),
        ),
        migrations.CreateModel(
            name='EventWork',
            fields=[
                ('tempentityclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_metainfo.tempentityclass')),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
            bases=('apis_metainfo.tempentityclass',),
        ),
        migrations.CreateModel(
            name='ExpressionWork',
            fields=[
                ('tempentityclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_metainfo.tempentityclass')),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
            bases=('apis_metainfo.tempentityclass',),
        ),
        migrations.CreateModel(
            name='InstitutionEvent',
            fields=[
                ('tempentityclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_metainfo.tempentityclass')),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
            bases=('apis_metainfo.tempentityclass',),
        ),
        migrations.CreateModel(
            name='InstitutionInstitution',
            fields=[
                ('tempentityclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_metainfo.tempentityclass')),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
            bases=('apis_metainfo.tempentityclass',),
        ),
        migrations.CreateModel(
            name='InstitutionPlace',
            fields=[
                ('tempentityclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_metainfo.tempentityclass')),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
            bases=('apis_metainfo.tempentityclass',),
        ),
        migrations.CreateModel(
            name='InstitutionWork',
            fields=[
                ('tempentityclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_metainfo.tempentityclass')),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
            bases=('apis_metainfo.tempentityclass',),
        ),
        migrations.CreateModel(
            name='ManuscriptExpression',
            fields=[
                ('tempentityclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_metainfo.tempentityclass')),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
            bases=('apis_metainfo.tempentityclass',),
        ),
        migrations.CreateModel(
            name='ManuscriptInstitution',
            fields=[
                ('tempentityclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_metainfo.tempentityclass')),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
            bases=('apis_metainfo.tempentityclass',),
        ),
        migrations.CreateModel(
            name='ManuscriptPerson',
            fields=[
                ('tempentityclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_metainfo.tempentityclass')),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
            bases=('apis_metainfo.tempentityclass',),
        ),
        migrations.CreateModel(
            name='ManuscriptPlace',
            fields=[
                ('tempentityclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_metainfo.tempentityclass')),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
            bases=('apis_metainfo.tempentityclass',),
        ),
        migrations.CreateModel(
            name='ManuscriptWork',
            fields=[
                ('tempentityclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_metainfo.tempentityclass')),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
            bases=('apis_metainfo.tempentityclass',),
        ),
        migrations.CreateModel(
            name='PersonEvent',
            fields=[
                ('tempentityclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_metainfo.tempentityclass')),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
            bases=('apis_metainfo.tempentityclass',),
        ),
        migrations.CreateModel(
            name='PersonInstitution',
            fields=[
                ('tempentityclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_metainfo.tempentityclass')),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
            bases=('apis_metainfo.tempentityclass',),
        ),
        migrations.CreateModel(
            name='PersonPerson',
            fields=[
                ('tempentityclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_metainfo.tempentityclass')),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
            bases=('apis_metainfo.tempentityclass',),
        ),
        migrations.CreateModel(
            name='PersonPlace',
            fields=[
                ('tempentityclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_metainfo.tempentityclass')),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
            bases=('apis_metainfo.tempentityclass',),
        ),
        migrations.CreateModel(
            name='PersonWork',
            fields=[
                ('tempentityclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_metainfo.tempentityclass')),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
            bases=('apis_metainfo.tempentityclass',),
        ),
        migrations.CreateModel(
            name='PlaceEvent',
            fields=[
                ('tempentityclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_metainfo.tempentityclass')),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
            bases=('apis_metainfo.tempentityclass',),
        ),
        migrations.CreateModel(
            name='PlacePlace',
            fields=[
                ('tempentityclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_metainfo.tempentityclass')),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
            bases=('apis_metainfo.tempentityclass',),
        ),
        migrations.CreateModel(
            name='PlaceWork',
            fields=[
                ('tempentityclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_metainfo.tempentityclass')),
                ('related_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placework_set', to='apis_entities.place')),
                ('related_work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placework_set', to='apis_entities.work')),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
            bases=('apis_metainfo.tempentityclass',),
        ),
    ]
