# Generated by Django 3.1.14 on 2022-09-14 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apis_vocabularies', '0001_initial'),
        ('apis_relations', '0001_initial'),
        ('apis_entities', '0002_auto_20220914_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='workwork',
            name='relation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workwork_set', to='apis_vocabularies.workworkrelation'),
        ),
        migrations.AddField(
            model_name='workmanuscriptpart',
            name='related_manuscriptpart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workmanuscriptpart_set', to='apis_entities.manuscriptpart'),
        ),
        migrations.AddField(
            model_name='workmanuscriptpart',
            name='related_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workmanuscriptpart_set', to='apis_entities.work'),
        ),
        migrations.AddField(
            model_name='workmanuscriptpart',
            name='relation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workmanuscriptpart_set', to='apis_vocabularies.workmanuscriptpartrelation'),
        ),
        migrations.AddField(
            model_name='placework',
            name='related_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placework_set', to='apis_entities.place'),
        ),
        migrations.AddField(
            model_name='placework',
            name='related_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placework_set', to='apis_entities.work'),
        ),
        migrations.AddField(
            model_name='placework',
            name='relation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placework_set', to='apis_vocabularies.placeworkrelation'),
        ),
        migrations.AddField(
            model_name='placeplace',
            name='related_placeA',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_placeB', to='apis_entities.place'),
        ),
        migrations.AddField(
            model_name='placeplace',
            name='related_placeB',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_placeA', to='apis_entities.place'),
        ),
        migrations.AddField(
            model_name='placeplace',
            name='relation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placeplace_set', to='apis_vocabularies.placeplacerelation'),
        ),
        migrations.AddField(
            model_name='placemanuscriptpart',
            name='related_manuscriptpart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placemanuscriptpart_set', to='apis_entities.manuscriptpart'),
        ),
        migrations.AddField(
            model_name='placemanuscriptpart',
            name='related_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placemanuscriptpart_set', to='apis_entities.place'),
        ),
        migrations.AddField(
            model_name='placemanuscriptpart',
            name='relation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placemanuscriptpart_set', to='apis_vocabularies.placemanuscriptpartrelation'),
        ),
        migrations.AddField(
            model_name='placeexpression',
            name='related_expression',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placeexpression_set', to='apis_entities.expression'),
        ),
        migrations.AddField(
            model_name='placeexpression',
            name='related_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placeexpression_set', to='apis_entities.place'),
        ),
        migrations.AddField(
            model_name='placeexpression',
            name='relation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placeexpression_set', to='apis_vocabularies.placeexpressionrelation'),
        ),
        migrations.AddField(
            model_name='placeevent',
            name='related_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placeevent_set', to='apis_entities.event'),
        ),
        migrations.AddField(
            model_name='placeevent',
            name='related_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placeevent_set', to='apis_entities.place'),
        ),
        migrations.AddField(
            model_name='placeevent',
            name='relation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placeevent_set', to='apis_vocabularies.placeeventrelation'),
        ),
        migrations.AddField(
            model_name='personwork',
            name='related_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personwork_set', to='apis_entities.person'),
        ),
        migrations.AddField(
            model_name='personwork',
            name='related_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personwork_set', to='apis_entities.work'),
        ),
        migrations.AddField(
            model_name='personwork',
            name='relation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personwork_set', to='apis_vocabularies.personworkrelation'),
        ),
        migrations.AddField(
            model_name='personplace',
            name='related_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personplace_set', to='apis_entities.person'),
        ),
        migrations.AddField(
            model_name='personplace',
            name='related_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personplace_set', to='apis_entities.place'),
        ),
        migrations.AddField(
            model_name='personplace',
            name='relation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personplace_set', to='apis_vocabularies.personplacerelation'),
        ),
        migrations.AddField(
            model_name='personperson',
            name='related_personA',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_personB', to='apis_entities.person'),
        ),
        migrations.AddField(
            model_name='personperson',
            name='related_personB',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_personA', to='apis_entities.person'),
        ),
        migrations.AddField(
            model_name='personperson',
            name='relation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personperson_set', to='apis_vocabularies.personpersonrelation'),
        ),
        migrations.AddField(
            model_name='personmanuscriptpart',
            name='related_manuscriptpart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personmanuscriptpart_set', to='apis_entities.manuscriptpart'),
        ),
        migrations.AddField(
            model_name='personmanuscriptpart',
            name='related_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personmanuscriptpart_set', to='apis_entities.person'),
        ),
        migrations.AddField(
            model_name='personmanuscriptpart',
            name='relation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personmanuscriptpart_set', to='apis_vocabularies.personmanuscriptpartrelation'),
        ),
        migrations.AddField(
            model_name='personinstitution',
            name='related_institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personinstitution_set', to='apis_entities.institution'),
        ),
        migrations.AddField(
            model_name='personinstitution',
            name='related_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personinstitution_set', to='apis_entities.person'),
        ),
        migrations.AddField(
            model_name='personinstitution',
            name='relation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personinstitution_set', to='apis_vocabularies.personinstitutionrelation'),
        ),
        migrations.AddField(
            model_name='personevent',
            name='related_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personevent_set', to='apis_entities.event'),
        ),
        migrations.AddField(
            model_name='personevent',
            name='related_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personevent_set', to='apis_entities.person'),
        ),
        migrations.AddField(
            model_name='personevent',
            name='relation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personevent_set', to='apis_vocabularies.personeventrelation'),
        ),
        migrations.AddField(
            model_name='manuscriptwork',
            name='related_manuscript',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manuscriptwork_set', to='apis_entities.manuscript'),
        ),
        migrations.AddField(
            model_name='manuscriptwork',
            name='related_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manuscriptwork_set', to='apis_entities.work'),
        ),
        migrations.AddField(
            model_name='manuscriptwork',
            name='relation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manuscriptwork_set', to='apis_vocabularies.manuscriptworkrelation'),
        ),
        migrations.AddField(
            model_name='manuscriptplace',
            name='related_manuscript',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manuscriptplace_set', to='apis_entities.manuscript'),
        ),
        migrations.AddField(
            model_name='manuscriptplace',
            name='related_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manuscriptplace_set', to='apis_entities.place'),
        ),
        migrations.AddField(
            model_name='manuscriptplace',
            name='relation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manuscriptplace_set', to='apis_vocabularies.manuscriptplacerelation'),
        ),
        migrations.AddField(
            model_name='manuscriptperson',
            name='related_manuscript',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manuscriptperson_set', to='apis_entities.manuscript'),
        ),
        migrations.AddField(
            model_name='manuscriptperson',
            name='related_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manuscriptperson_set', to='apis_entities.person'),
        ),
        migrations.AddField(
            model_name='manuscriptperson',
            name='relation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manuscriptperson_set', to='apis_vocabularies.manuscriptpersonrelation'),
        ),
        migrations.AddField(
            model_name='manuscriptmanuscriptpart',
            name='related_manuscript',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manuscriptmanuscriptpart_set', to='apis_entities.manuscript'),
        ),
        migrations.AddField(
            model_name='manuscriptmanuscriptpart',
            name='related_manuscriptpart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manuscriptmanuscriptpart_set', to='apis_entities.manuscriptpart'),
        ),
        migrations.AddField(
            model_name='manuscriptmanuscriptpart',
            name='relation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manuscriptmanuscriptpart_set', to='apis_vocabularies.manuscriptmanuscriptpartrelation'),
        ),
        migrations.AddField(
            model_name='manuscriptinstitution',
            name='related_institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manuscriptinstitution_set', to='apis_entities.institution'),
        ),
        migrations.AddField(
            model_name='manuscriptinstitution',
            name='related_manuscript',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manuscriptinstitution_set', to='apis_entities.manuscript'),
        ),
        migrations.AddField(
            model_name='manuscriptinstitution',
            name='relation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manuscriptinstitution_set', to='apis_vocabularies.manuscriptinstitutionrelation'),
        ),
        migrations.AddField(
            model_name='manuscriptexpression',
            name='related_expression',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manuscriptexpression_set', to='apis_entities.expression'),
        ),
        migrations.AddField(
            model_name='manuscriptexpression',
            name='related_manuscript',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manuscriptexpression_set', to='apis_entities.manuscript'),
        ),
        migrations.AddField(
            model_name='manuscriptexpression',
            name='relation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manuscriptexpression_set', to='apis_vocabularies.manuscriptexpressionrelation'),
        ),
        migrations.AddField(
            model_name='institutionwork',
            name='related_institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institutionwork_set', to='apis_entities.institution'),
        ),
        migrations.AddField(
            model_name='institutionwork',
            name='related_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institutionwork_set', to='apis_entities.work'),
        ),
        migrations.AddField(
            model_name='institutionwork',
            name='relation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institutionwork_set', to='apis_vocabularies.institutionworkrelation'),
        ),
        migrations.AddField(
            model_name='institutionplace',
            name='related_institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institutionplace_set', to='apis_entities.institution'),
        ),
        migrations.AddField(
            model_name='institutionplace',
            name='related_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institutionplace_set', to='apis_entities.place'),
        ),
        migrations.AddField(
            model_name='institutionplace',
            name='relation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institutionplace_set', to='apis_vocabularies.institutionplacerelation'),
        ),
        migrations.AddField(
            model_name='institutionmanuscriptpart',
            name='related_institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institutionmanuscriptpart_set', to='apis_entities.institution'),
        ),
        migrations.AddField(
            model_name='institutionmanuscriptpart',
            name='related_manuscriptpart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institutionmanuscriptpart_set', to='apis_entities.manuscriptpart'),
        ),
        migrations.AddField(
            model_name='institutionmanuscriptpart',
            name='relation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institutionmanuscriptpart_set', to='apis_vocabularies.institutionmanuscriptpartrelation'),
        ),
        migrations.AddField(
            model_name='institutioninstitution',
            name='related_institutionA',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_institutionB', to='apis_entities.institution'),
        ),
        migrations.AddField(
            model_name='institutioninstitution',
            name='related_institutionB',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_institutionA', to='apis_entities.institution'),
        ),
        migrations.AddField(
            model_name='institutioninstitution',
            name='relation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institutioninstitution_set', to='apis_vocabularies.institutioninstitutionrelation'),
        ),
        migrations.AddField(
            model_name='institutionevent',
            name='related_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institutionevent_set', to='apis_entities.event'),
        ),
        migrations.AddField(
            model_name='institutionevent',
            name='related_institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institutionevent_set', to='apis_entities.institution'),
        ),
        migrations.AddField(
            model_name='institutionevent',
            name='relation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institutionevent_set', to='apis_vocabularies.institutioneventrelation'),
        ),
        migrations.AddField(
            model_name='expressionwork',
            name='related_expression',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expressionwork_set', to='apis_entities.expression'),
        ),
        migrations.AddField(
            model_name='expressionwork',
            name='related_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expressionwork_set', to='apis_entities.work'),
        ),
        migrations.AddField(
            model_name='expressionwork',
            name='relation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expressionwork_set', to='apis_vocabularies.expressionworkrelation'),
        ),
        migrations.AddField(
            model_name='expressionperson',
            name='related_expression',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expressionperson_set', to='apis_entities.expression'),
        ),
        migrations.AddField(
            model_name='expressionperson',
            name='related_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expressionperson_set', to='apis_entities.person'),
        ),
        migrations.AddField(
            model_name='expressionperson',
            name='relation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expressionperson_set', to='apis_vocabularies.expressionpersonrelation'),
        ),
        migrations.AddField(
            model_name='expressionmanuscriptpart',
            name='related_expression',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expressionmanuscriptpart_set', to='apis_entities.expression'),
        ),
        migrations.AddField(
            model_name='expressionmanuscriptpart',
            name='related_manuscriptpart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expressionmanuscriptpart_set', to='apis_entities.manuscriptpart'),
        ),
        migrations.AddField(
            model_name='expressionmanuscriptpart',
            name='relation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expressionmanuscriptpart_set', to='apis_vocabularies.expressionmanuscriptpartrelation'),
        ),
        migrations.AddField(
            model_name='eventwork',
            name='related_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventwork_set', to='apis_entities.event'),
        ),
        migrations.AddField(
            model_name='eventwork',
            name='related_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventwork_set', to='apis_entities.work'),
        ),
        migrations.AddField(
            model_name='eventwork',
            name='relation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventwork_set', to='apis_vocabularies.eventworkrelation'),
        ),
        migrations.AddField(
            model_name='eventevent',
            name='related_eventA',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_eventB', to='apis_entities.event'),
        ),
        migrations.AddField(
            model_name='eventevent',
            name='related_eventB',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_eventA', to='apis_entities.event'),
        ),
        migrations.AddField(
            model_name='eventevent',
            name='relation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventevent_set', to='apis_vocabularies.eventeventrelation'),
        ),
    ]
