# Generated by Django 3.1.14 on 2022-09-14 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis_entities', '0003_manuscriptpart'),
        ('apis_metainfo', '0002_auto_20220914_1322'),
        ('apis_vocabularies', '0002_expressionmanuscriptpartrelation_institutionmanuscriptpartrelation_manusciptparttype_manuscriptmanus'),
        ('apis_relations', '0002_auto_20220914_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkManuscriptpart',
            fields=[
                ('tempentityclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_metainfo.tempentityclass')),
                ('certainty', models.CharField(blank=True, choices=[(None, '---'), ('low', 'low'), ('medium', 'medium'), ('high', 'high')], help_text='Specify the certainty of this information.', max_length=10, null=True)),
                ('related_manuscriptpart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workmanuscriptpart_set', to='apis_entities.manuscriptpart')),
                ('related_work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workmanuscriptpart_set', to='apis_entities.work')),
                ('relation_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workmanuscriptpart_set', to='apis_vocabularies.workmanuscriptpartrelation')),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
            bases=('apis_metainfo.tempentityclass',),
        ),
        migrations.CreateModel(
            name='PlaceManuscriptpart',
            fields=[
                ('tempentityclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_metainfo.tempentityclass')),
                ('certainty', models.CharField(blank=True, choices=[(None, '---'), ('low', 'low'), ('medium', 'medium'), ('high', 'high')], help_text='Specify the certainty of this information.', max_length=10, null=True)),
                ('related_manuscriptpart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placemanuscriptpart_set', to='apis_entities.manuscriptpart')),
                ('related_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placemanuscriptpart_set', to='apis_entities.place')),
                ('relation_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placemanuscriptpart_set', to='apis_vocabularies.placemanuscriptpartrelation')),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
            bases=('apis_metainfo.tempentityclass',),
        ),
        migrations.CreateModel(
            name='PersonManuscriptpart',
            fields=[
                ('tempentityclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_metainfo.tempentityclass')),
                ('certainty', models.CharField(blank=True, choices=[(None, '---'), ('low', 'low'), ('medium', 'medium'), ('high', 'high')], help_text='Specify the certainty of this information.', max_length=10, null=True)),
                ('related_manuscriptpart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personmanuscriptpart_set', to='apis_entities.manuscriptpart')),
                ('related_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personmanuscriptpart_set', to='apis_entities.person')),
                ('relation_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personmanuscriptpart_set', to='apis_vocabularies.personmanuscriptpartrelation')),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
            bases=('apis_metainfo.tempentityclass',),
        ),
        migrations.CreateModel(
            name='ManuscriptManuscriptpart',
            fields=[
                ('tempentityclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_metainfo.tempentityclass')),
                ('certainty', models.CharField(blank=True, choices=[(None, '---'), ('low', 'low'), ('medium', 'medium'), ('high', 'high')], help_text='Specify the certainty of this information.', max_length=10, null=True)),
                ('related_manuscript', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manuscriptmanuscriptpart_set', to='apis_entities.manuscript')),
                ('related_manuscriptpart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manuscriptmanuscriptpart_set', to='apis_entities.manuscriptpart')),
                ('relation_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manuscriptmanuscriptpart_set', to='apis_vocabularies.manuscriptmanuscriptpartrelation')),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
            bases=('apis_metainfo.tempentityclass',),
        ),
        migrations.CreateModel(
            name='InstitutionManuscriptpart',
            fields=[
                ('tempentityclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_metainfo.tempentityclass')),
                ('certainty', models.CharField(blank=True, choices=[(None, '---'), ('low', 'low'), ('medium', 'medium'), ('high', 'high')], help_text='Specify the certainty of this information.', max_length=10, null=True)),
                ('related_institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institutionmanuscriptpart_set', to='apis_entities.institution')),
                ('related_manuscriptpart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institutionmanuscriptpart_set', to='apis_entities.manuscriptpart')),
                ('relation_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institutionmanuscriptpart_set', to='apis_vocabularies.institutionmanuscriptpartrelation')),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
            bases=('apis_metainfo.tempentityclass',),
        ),
        migrations.CreateModel(
            name='ExpressionManuscriptpart',
            fields=[
                ('tempentityclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_metainfo.tempentityclass')),
                ('certainty', models.CharField(blank=True, choices=[(None, '---'), ('low', 'low'), ('medium', 'medium'), ('high', 'high')], help_text='Specify the certainty of this information.', max_length=10, null=True)),
                ('related_expression', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expressionmanuscriptpart_set', to='apis_entities.expression')),
                ('related_manuscriptpart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expressionmanuscriptpart_set', to='apis_entities.manuscriptpart')),
                ('relation_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expressionmanuscriptpart_set', to='apis_vocabularies.expressionmanuscriptpartrelation')),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
            bases=('apis_metainfo.tempentityclass',),
        ),
    ]
