# Generated by Django 3.1.8 on 2022-04-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_relations', '0002_auto_20220408_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventevent',
            name='certainty',
            field=models.CharField(blank=True, choices=[(None, '---'), ('low', 'low'), ('medium', 'medium'), ('high', 'high')], help_text='Specify the certainty of this information.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='eventwork',
            name='certainty',
            field=models.CharField(blank=True, choices=[(None, '---'), ('low', 'low'), ('medium', 'medium'), ('high', 'high')], help_text='Specify the certainty of this information.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='expressionwork',
            name='certainty',
            field=models.CharField(blank=True, choices=[(None, '---'), ('low', 'low'), ('medium', 'medium'), ('high', 'high')], help_text='Specify the certainty of this information.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='institutionevent',
            name='certainty',
            field=models.CharField(blank=True, choices=[(None, '---'), ('low', 'low'), ('medium', 'medium'), ('high', 'high')], help_text='Specify the certainty of this information.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='institutioninstitution',
            name='certainty',
            field=models.CharField(blank=True, choices=[(None, '---'), ('low', 'low'), ('medium', 'medium'), ('high', 'high')], help_text='Specify the certainty of this information.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='institutionplace',
            name='certainty',
            field=models.CharField(blank=True, choices=[(None, '---'), ('low', 'low'), ('medium', 'medium'), ('high', 'high')], help_text='Specify the certainty of this information.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='institutionwork',
            name='certainty',
            field=models.CharField(blank=True, choices=[(None, '---'), ('low', 'low'), ('medium', 'medium'), ('high', 'high')], help_text='Specify the certainty of this information.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='manuscriptexpression',
            name='certainty',
            field=models.CharField(blank=True, choices=[(None, '---'), ('low', 'low'), ('medium', 'medium'), ('high', 'high')], help_text='Specify the certainty of this information.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='manuscriptinstitution',
            name='certainty',
            field=models.CharField(blank=True, choices=[(None, '---'), ('low', 'low'), ('medium', 'medium'), ('high', 'high')], help_text='Specify the certainty of this information.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='manuscriptperson',
            name='certainty',
            field=models.CharField(blank=True, choices=[(None, '---'), ('low', 'low'), ('medium', 'medium'), ('high', 'high')], help_text='Specify the certainty of this information.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='manuscriptplace',
            name='certainty',
            field=models.CharField(blank=True, choices=[(None, '---'), ('low', 'low'), ('medium', 'medium'), ('high', 'high')], help_text='Specify the certainty of this information.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='manuscriptwork',
            name='certainty',
            field=models.CharField(blank=True, choices=[(None, '---'), ('low', 'low'), ('medium', 'medium'), ('high', 'high')], help_text='Specify the certainty of this information.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='personevent',
            name='certainty',
            field=models.CharField(blank=True, choices=[(None, '---'), ('low', 'low'), ('medium', 'medium'), ('high', 'high')], help_text='Specify the certainty of this information.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='personinstitution',
            name='certainty',
            field=models.CharField(blank=True, choices=[(None, '---'), ('low', 'low'), ('medium', 'medium'), ('high', 'high')], help_text='Specify the certainty of this information.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='personperson',
            name='certainty',
            field=models.CharField(blank=True, choices=[(None, '---'), ('low', 'low'), ('medium', 'medium'), ('high', 'high')], help_text='Specify the certainty of this information.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='personplace',
            name='certainty',
            field=models.CharField(blank=True, choices=[(None, '---'), ('low', 'low'), ('medium', 'medium'), ('high', 'high')], help_text='Specify the certainty of this information.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='personwork',
            name='certainty',
            field=models.CharField(blank=True, choices=[(None, '---'), ('low', 'low'), ('medium', 'medium'), ('high', 'high')], help_text='Specify the certainty of this information.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='placeevent',
            name='certainty',
            field=models.CharField(blank=True, choices=[(None, '---'), ('low', 'low'), ('medium', 'medium'), ('high', 'high')], help_text='Specify the certainty of this information.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='placeplace',
            name='certainty',
            field=models.CharField(blank=True, choices=[(None, '---'), ('low', 'low'), ('medium', 'medium'), ('high', 'high')], help_text='Specify the certainty of this information.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='placework',
            name='certainty',
            field=models.CharField(blank=True, choices=[(None, '---'), ('low', 'low'), ('medium', 'medium'), ('high', 'high')], help_text='Specify the certainty of this information.', max_length=10, null=True),
        ),
    ]
