# Generated by Django 3.1.8 on 2022-04-26 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis_entities', '0003_auto_20220426_0822'),
        ('apis_metainfo', '0002_auto_20220408_1654'),
        ('apis_vocabularies', '0004_expressionpersonrelation'),
        ('apis_relations', '0003_auto_20220425_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpressionPerson',
            fields=[
                ('tempentityclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_metainfo.tempentityclass')),
                ('certainty', models.CharField(blank=True, choices=[(None, '---'), ('low', 'low'), ('medium', 'medium'), ('high', 'high')], help_text='Specify the certainty of this information.', max_length=10, null=True)),
                ('related_expression', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expressionperson_set', to='apis_entities.expression')),
                ('related_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expressionperson_set', to='apis_entities.person')),
                ('relation_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expressionperson_set', to='apis_vocabularies.expressionpersonrelation')),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
            bases=('apis_metainfo.tempentityclass',),
        ),
    ]
