# Generated by Django 3.1.8 on 2022-06-10 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis_entities', '0004_auto_20220426_1816'),
        ('apis_metainfo', '0002_auto_20220408_1654'),
        ('apis_relations', '0004_expressionperson'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkWork',
            fields=[
                ('tempentityclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_metainfo.tempentityclass')),
                ('certainty', models.CharField(blank=True, choices=[(None, '---'), ('low', 'low'), ('medium', 'medium'), ('high', 'high')], help_text='Specify the certainty of this information.', max_length=10, null=True)),
                ('related_workA', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_workB', to='apis_entities.work')),
                ('related_workB', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_workA', to='apis_entities.work')),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
            bases=('apis_metainfo.tempentityclass',),
        ),
    ]
