# Generated by Django 3.1.8 on 2022-06-10 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis_vocabularies', '0005_workworkrelation'),
        ('apis_relations', '0005_workwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='workwork',
            name='relation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workwork_set', to='apis_vocabularies.workworkrelation'),
        ),
    ]
