# Generated by Django 3.1.8 on 2022-04-26 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis_vocabularies', '0003_scripttype'),
        ('apis_entities', '0002_auto_20220408_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='expression',
            name='script_body',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ScriptTypeBody_set', to='apis_vocabularies.scripttype'),
        ),
        migrations.AddField(
            model_name='expression',
            name='script_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ScriptTypeTitle_set', to='apis_vocabularies.scripttype'),
        ),
    ]
