# Generated by Django 3.1.14 on 2022-09-14 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis_metainfo', '0002_auto_20220914_1322'),
        ('apis_entities', '0002_auto_20220914_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manuscriptpart',
            fields=[
                ('tempentityclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_metainfo.tempentityclass')),
                ('identifier', models.CharField(max_length=255)),
                ('locus', models.CharField(blank=True, help_text='Locus of the manuscript part', max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('apis_metainfo.tempentityclass',),
        ),
    ]
