# Generated by Django 3.1.14 on 2022-09-14 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis_entities', '0003_manuscriptpart'),
        ('apis_vocabularies', '0002_expressionmanuscriptpartrelation_institutionmanuscriptpartrelation_manusciptparttype_manuscriptmanus'),
        ('apis_relations', '0003_expressionmanuscriptpart_institutionmanuscriptpart_manuscriptmanuscriptpart_personmanuscriptpart_pla'),
    ]

    operations = [
        migrations.AddField(
            model_name='expression',
            name='manuscriptpart_relationtype_set',
            field=models.ManyToManyField(blank=True, related_name='expression_set', through='apis_relations.ExpressionManuscriptpart', to='apis_vocabularies.ExpressionManuscriptpartRelation'),
        ),
        migrations.AddField(
            model_name='institution',
            name='manuscriptpart_relationtype_set',
            field=models.ManyToManyField(blank=True, related_name='institution_set', through='apis_relations.InstitutionManuscriptpart', to='apis_vocabularies.InstitutionManuscriptpartRelation'),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='manuscriptpart_relationtype_set',
            field=models.ManyToManyField(blank=True, related_name='manuscript_set', through='apis_relations.ManuscriptManuscriptpart', to='apis_vocabularies.ManuscriptManuscriptpartRelation'),
        ),
        migrations.AddField(
            model_name='person',
            name='manuscriptpart_relationtype_set',
            field=models.ManyToManyField(blank=True, related_name='person_set', through='apis_relations.PersonManuscriptpart', to='apis_vocabularies.PersonManuscriptpartRelation'),
        ),
        migrations.AddField(
            model_name='place',
            name='manuscriptpart_relationtype_set',
            field=models.ManyToManyField(blank=True, related_name='place_set', through='apis_relations.PlaceManuscriptpart', to='apis_vocabularies.PlaceManuscriptpartRelation'),
        ),
        migrations.AddField(
            model_name='work',
            name='manuscriptpart_relationtype_set',
            field=models.ManyToManyField(blank=True, related_name='work_set', through='apis_relations.WorkManuscriptpart', to='apis_vocabularies.WorkManuscriptpartRelation'),
        ),
        migrations.AddField(
            model_name='manuscriptpart',
            name='expression_relationtype_set',
            field=models.ManyToManyField(blank=True, related_name='manuscriptpart_set', through='apis_relations.ExpressionManuscriptpart', to='apis_vocabularies.ExpressionManuscriptpartRelation'),
        ),
        migrations.AddField(
            model_name='manuscriptpart',
            name='institution_relationtype_set',
            field=models.ManyToManyField(blank=True, related_name='manuscriptpart_set', through='apis_relations.InstitutionManuscriptpart', to='apis_vocabularies.InstitutionManuscriptpartRelation'),
        ),
        migrations.AddField(
            model_name='manuscriptpart',
            name='manuscript_relationtype_set',
            field=models.ManyToManyField(blank=True, related_name='manuscriptpart_set', through='apis_relations.ManuscriptManuscriptpart', to='apis_vocabularies.ManuscriptManuscriptpartRelation'),
        ),
        migrations.AddField(
            model_name='manuscriptpart',
            name='person_relationtype_set',
            field=models.ManyToManyField(blank=True, related_name='manuscriptpart_set', through='apis_relations.PersonManuscriptpart', to='apis_vocabularies.PersonManuscriptpartRelation'),
        ),
        migrations.AddField(
            model_name='manuscriptpart',
            name='place_relationtype_set',
            field=models.ManyToManyField(blank=True, related_name='manuscriptpart_set', through='apis_relations.PlaceManuscriptpart', to='apis_vocabularies.PlaceManuscriptpartRelation'),
        ),
        migrations.AddField(
            model_name='manuscriptpart',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis_vocabularies.manusciptparttype'),
        ),
        migrations.AddField(
            model_name='manuscriptpart',
            name='work_relationtype_set',
            field=models.ManyToManyField(blank=True, related_name='manuscriptpart_set', through='apis_relations.WorkManuscriptpart', to='apis_vocabularies.WorkManuscriptpartRelation'),
        ),
        migrations.AddField(
            model_name='expression',
            name='manuscriptpart_set',
            field=models.ManyToManyField(blank=True, related_name='expression_set', through='apis_relations.ExpressionManuscriptpart', to='apis_entities.Manuscriptpart'),
        ),
        migrations.AddField(
            model_name='institution',
            name='manuscriptpart_set',
            field=models.ManyToManyField(blank=True, related_name='institution_set', through='apis_relations.InstitutionManuscriptpart', to='apis_entities.Manuscriptpart'),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='manuscriptpart_set',
            field=models.ManyToManyField(blank=True, related_name='manuscript_set', through='apis_relations.ManuscriptManuscriptpart', to='apis_entities.Manuscriptpart'),
        ),
        migrations.AddField(
            model_name='person',
            name='manuscriptpart_set',
            field=models.ManyToManyField(blank=True, related_name='person_set', through='apis_relations.PersonManuscriptpart', to='apis_entities.Manuscriptpart'),
        ),
        migrations.AddField(
            model_name='place',
            name='manuscriptpart_set',
            field=models.ManyToManyField(blank=True, related_name='place_set', through='apis_relations.PlaceManuscriptpart', to='apis_entities.Manuscriptpart'),
        ),
        migrations.AddField(
            model_name='work',
            name='manuscriptpart_set',
            field=models.ManyToManyField(blank=True, related_name='work_set', through='apis_relations.WorkManuscriptpart', to='apis_entities.Manuscriptpart'),
        ),
    ]
