# Generated by Django 3.1.8 on 2022-04-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_relations', '0004_expressionperson'),
        ('apis_vocabularies', '0004_expressionpersonrelation'),
        ('apis_entities', '0003_auto_20220426_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='expression',
            name='person_relationtype_set',
            field=models.ManyToManyField(blank=True, related_name='expression_set', through='apis_relations.ExpressionPerson', to='apis_vocabularies.ExpressionPersonRelation'),
        ),
        migrations.AddField(
            model_name='expression',
            name='person_set',
            field=models.ManyToManyField(blank=True, related_name='expression_set', through='apis_relations.ExpressionPerson', to='apis_entities.Person'),
        ),
        migrations.AddField(
            model_name='person',
            name='expression_relationtype_set',
            field=models.ManyToManyField(blank=True, related_name='person_set', through='apis_relations.ExpressionPerson', to='apis_vocabularies.ExpressionPersonRelation'),
        ),
    ]
