# Generated by Django 3.1.8 on 2022-06-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_vocabularies', '0005_workworkrelation'),
        ('apis_relations', '0005_workwork'),
        ('apis_entities', '0004_auto_20220426_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='workB_relationtype_set',
            field=models.ManyToManyField(blank=True, related_name='workA_set', through='apis_relations.WorkWork', to='apis_vocabularies.WorkWorkRelation'),
        ),
        migrations.AddField(
            model_name='work',
            name='workB_set',
            field=models.ManyToManyField(blank=True, related_name='workA_set', through='apis_relations.WorkWork', to='apis_entities.Work'),
        ),
    ]
