# Generated by Django 3.1.8 on 2022-04-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_labels', '0002_auto_20220408_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='arabic_script',
            field=models.CharField(blank=True, help_text='Label in arabic script if needed', max_length=255, null=True),
        ),
    ]
