# Generated by Django 3.2.6 on 2021-08-11 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis_vocabularies', '0003_transliterationtype'),
        ('apis_labels', '0003_auto_20200221_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='transliteration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis_vocabularies.transliterationtype'),
        ),
    ]
