# Generated by Django 3.1.14 on 2022-09-14 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis_vocabularies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpressionManuscriptpartRelation',
            fields=[
                ('relationbaseclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_vocabularies.relationbaseclass')),
            ],
            options={
                'abstract': False,
            },
            bases=('apis_vocabularies.relationbaseclass',),
        ),
        migrations.CreateModel(
            name='InstitutionManuscriptpartRelation',
            fields=[
                ('relationbaseclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_vocabularies.relationbaseclass')),
            ],
            options={
                'abstract': False,
            },
            bases=('apis_vocabularies.relationbaseclass',),
        ),
        migrations.CreateModel(
            name='ManusciptpartType',
            fields=[
                ('vocabsbaseclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_vocabularies.vocabsbaseclass')),
            ],
            bases=('apis_vocabularies.vocabsbaseclass',),
        ),
        migrations.CreateModel(
            name='ManuscriptManuscriptpartRelation',
            fields=[
                ('relationbaseclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_vocabularies.relationbaseclass')),
            ],
            options={
                'abstract': False,
            },
            bases=('apis_vocabularies.relationbaseclass',),
        ),
        migrations.CreateModel(
            name='PersonManuscriptpartRelation',
            fields=[
                ('relationbaseclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_vocabularies.relationbaseclass')),
            ],
            options={
                'abstract': False,
            },
            bases=('apis_vocabularies.relationbaseclass',),
        ),
        migrations.CreateModel(
            name='PlaceManuscriptpartRelation',
            fields=[
                ('relationbaseclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_vocabularies.relationbaseclass')),
            ],
            options={
                'abstract': False,
            },
            bases=('apis_vocabularies.relationbaseclass',),
        ),
        migrations.CreateModel(
            name='WorkManuscriptpartRelation',
            fields=[
                ('relationbaseclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_vocabularies.relationbaseclass')),
            ],
            options={
                'abstract': False,
            },
            bases=('apis_vocabularies.relationbaseclass',),
        ),
    ]
