# Generated by Django 3.2.6 on 2021-08-11 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis_vocabularies', '0002_texttype_lang'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransliterationType',
            fields=[
                ('vocabsbaseclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_vocabularies.vocabsbaseclass')),
            ],
            bases=('apis_vocabularies.vocabsbaseclass',),
        ),
    ]
